### ISSUE TITLE
Seems to not deal with templated dates correctly

### ISSUE THREAD

**Issue by fakeharxy** [ryanjamurphy/review-obsidian#22]
This could be PICNIC but I'm having issues with my template and Review. In my daily note template I have the following:

```
[[{{tp_title_yesterday:title_f=DD MMM YYYY,f=DD MMM YYYY}}|<<<]] || [[{{tp_title_tomorrow:title_f=DD MMM YYYY,f=DD MMM YYYY}}|>>>]]
```

This is suppose to display as <<< || >>> with the arrows as links to the previous/next notes, and works correctly when the daily note is created with Calendar or the Daily Note Hotkey.

When I select a task (block) to Review, if the daily note needs to be created by Review (which is usually the case, being the future) I get this output:

![Screenshot 2021-03-23 at 11 00 08](https://user-images.githubusercontent.com/23191321/112136505-f1b6b300-8bc6-11eb-953c-21dc9e0d4af2.png)

It's puzzling as I don't know what Review would be doing differently to the other methods of creating a note.

Thanks for any help (and creating a great plugin).

**Comment by meskill** [comment]
Same issue here - most templates works just fine, except for templates which includes parsing filename title

**Comment by ryanjamurphy** [comment]
Interesting. Thanks for the report. I also get a similar problem with Periodic Dates' date math (which does basically the same thing as Templater's date feature).

I think this is actually caused by Review's reliance on the Daily Notes Interface made by @liamcain—that interface handles note creation. Liam, I note that the interface readme includes a description of `getTemplateInfo`, which states:
> Generic utility for reading the contents of a file given it's relative path. This does not apply any transformations.

Does this mean the interface doesn't currently handle the expansion of template strings like those from Templater and Periodic Notes?

**Comment by liamcain** [comment]
This report looks to be a bug in the Templater  plugin (which just received a complete overhaul today).

> Liam, I note that the interface readme includes a description of getTemplateInfo, which states:

You're not using the `getTemplateInfo` function at all, so that's not an issue.

> I also get a similar problem with Periodic Dates' date math (which does basically the same thing as Templater's date feature).

If you want that behavior to happen in the Review plugin, you'll need to update your version of the `daily-notes-interface` package that you're using. That behavior got added in `0.8.X`. You're using [`v0.7.0`](https://github.com/ryanjamurphy/review-obsidian/blob/e8bb38c12297858773555b79f59e37c8d3d25b27/package.json#L25)

**Comment by ryanjamurphy** [comment]
D'oh. I ran `npm update` before my comment above, but I hadn't realized I had to advance the version requirement in the ~~rollup~~ `package.json` file. 

Pushing an update that'll get this working with Periodic Notes in a moment!

@meskill / @fakeharxy — mind testing with the new edition of Templater and reporting back?

**Comment by fakeharxy** [comment]
@ryanjamurphy That has fixed the issue, at least for me! Thanks all

**Comment by meskill** [comment]
@ryanjamurphy it is working fine with the latest version, thank you

I think issue might be closed now

**Comment by ryanjamurphy** [comment]
Thanks all!
